### ISSUE TITLE
Can't install Haguichi on Raspbian

### ISSUE THREAD

**Issue by mmautomatizacion** [ztefn/haguichi#14]
Hi,
I'm trying to install Haguichi on Raspbian. I'm following the steps indicated on Haguichi website for Raspbian, but when I execute this command:

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C2518248EEA14886`

I receive this error:

`gpg: keyserver receive failed: No dirmngr`

What am I doing wrong? Thanks

**Comment by ztefn** [comment]
For some mysterious reason dirmngr is no longer installed by default in [Debian](https://unix.stackexchange.com/questions/401547/gpg-keyserver-receive-failed-no-dirmngr) and [Raspian](https://www.raspberrypi.org/forums/viewtopic.php?t=193536) since Stretch. You can do so by entering:
`sudo apt-get install dirmngr`

**Comment by mmautomatizacion** [comment]
Thanks, works correctly.
