### ISSUE TITLE
Good Way to Install on CentOS 7?

### ISSUE THREAD

**Issue by tvollscw** [ztefn/haguichi#17]
I know this probably isn't requested often, but I'm running CentOS 7 with Gnome Classic as a GUI, and I was wondering if there was a way to install Haguichi on CentOS 7? On the official download page, I see instructions for Fedora using dnf, but CentOS does not have dnf, so I was wondering if there was way to install it on CentOS over yum.

**Comment by ztefn** [comment]
Sure, you can install the RPM package generated by Copr for Fedora 28 without any troubles—restarting the service after configuring actually works!—on CentOS 7 using yum:
`https://copr-be.cloud.fedoraproject.org/results/ztefn/haguichi/fedora-28-x86_64/00752358-haguichi/haguichi-1.4.0-3.1.x86_64.rpm`
`sudo yum install haguichi-1.4.0-3.1.x86_64.rpm`

Off course these command above only work for the current build. Once there is a new build the download URL and filename will change. You can find the latest builds here: https://copr.fedorainfracloud.org/coprs/ztefn/haguichi/builds/ Click the latest one and then choose the best matching distro (i.e. Fedora 28 x86_64) and then download the normal RPM.

I don't have any official downloads for CentOS because both openSUSE Build Service and Copr fail to build Haguichi on CentOS/EPEL because of outdated or bad [meson](http://mesonbuild.com/) versions.
