### ISSUE TITLE
Java8 JDK :D

### ISSUE THREAD

**Issue by jduyon** [ztefn/haguichi#21]
This isn't an issue. I just noticed you are a member of the webupd8 team (https://launchpad.net/~webupd8team/+archive/ubuntu/java) and the oracle-java8-installer packaging is currently redirecting to a 404 on Oracle's website.
 
Could you republish the package with an updated url, or contact someone who is able to?

**Comment by ztefn** [comment]
I'm a member of wepupd8team so that I can publish new Haguichi releases to its own PPA (https://launchpad.net/~webupd8team/+archive/ubuntu/haguichi).

I have no knowledge of Java SDK packaging. Only Alin Andrei (aka Andrew) is able to update it. He probably did receive your e-mail but hasn't got around to it. After all, you just sent it one day ago. I think you need a little more patience...
