### ISSUE TITLE
Publish app on AppCenter (elementary OS)

### ISSUE THREAD

**Issue by jtrees** [ztefn/haguichi#3]
I love your app and find it fits into the elementary OS environment perfectly. Have you considered [publishing it on their AppCenter](https://developer.elementary.io/)? It would greatly increase visibility.

**Comment by ztefn** [comment]
Hi Joshua,

Yes, I have considered publishing to AppCenter when it launched, but hadn't followed through with that yet because it requires some branching from the master version to accommodate elementaryOS specific stuff. But I think now is a good time to give it a shot and see what it takes. So I created a [separate branch for elementaryOS](https://github.com/ztefn/haguichi/tree/elementary).

I changed the GUI to fit elementaryOS even better (see the [screenshots](https://github.com/ztefn/haguichi/tree/elementary/data/screenshots)), because the dark theme on elementaryOS has [some](https://github.com/elementary/stylesheet/issues/97) [issues](https://github.com/elementary/stylesheet/issues/98) (and they don't care apparently, since they never replied).

Anyway, I've pushed the [first alpha](https://github.com/ztefn/haguichi/releases/tag/1.3.8-alpha) to the AppCenter. This will probably report back with multitude of issues for a while. The first issue I encounter is on the dashboard itself:
_**Error Encountered Processing com.github.ztefn.haguichi.**
This is most likely a problem with this website._

So... i guess we'll see how this goes...

**Comment by ztefn** [comment]
I have good news: All issues have been resolved (kudos @btkostner) and Haguichi is now published on AppCenter!

[![Get it on AppCenter](https://appcenter.elementary.io/badge.svg)](https://appcenter.elementary.io/com.github.ztefn.haguichi)﻿

If you have Haguichi installed from PPA, you can remove this version by entering the following commands in a terminal:
`sudo apt update`
`sudo apt install ppa-purge`
`sudo ppa-purge ppa:webupd8team/haguichi`

There is one thing missing compared to the vanilla version, that is the indicator in the panel. Currently this is a separate package and that's not very practical for distribution through AppCenter. So my plan is to integrate the indicator into Haguichi itself in one of the next releases, providing a switch to enable/disable it.

**Comment by jtrees** [comment]
Saweeet! Thanks and thank you also for the instructions on how to remove the PPA.

I noticed though that my client no longer uses the dark theme and I didn't find an option for it in the preferences. How do I re-enable it?

**Comment by ztefn** [comment]
Using the dark theme things look a bit off, even more so now with the colored headerbar. But if you still prefer, you can re-enable it via gsettings:
`gsettings set com.github.ztefn.haguichi.ui prefer-dark-theme true`

Use _false_ instead of _true_ if you want to disable the dark theme again. You can also use dconf-editor to browse and change all hidden advanced settings.

**Comment by ztefn** [comment]
[Official announcement](https://www.haguichi.net/news/haguichi-is-now-available-on-elementary-os-appcenter/) 🎉

**Comment by ztefn** [comment]
Issues with the dark theme have been resolved in version 1.138.2 by embedding a [special stylesheet](https://github.com/ztefn/haguichi/blob/elementary/data/stylesheets/elementary-dark.css) into Haguichi itself.
