### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by mcdelarosa** [ztefn/haguichi#30]
I have Hamachi and Haguichi in Ubuntu 20.04 but it disconnects constantly from the network, I've tried to make the network but it happens the same thing.

**Comment by ztefn** [comment]
Haguichi is just a graphical frontend for Hamachi. If you have connection issues the problem is with Hamachi itself and/or your network infrastructure (firewall, etc.). You can find the Hamachi log file at **/var/lib/logmein-hamachi/h2-engine.log** and LogMeIn Hamachi help and support at https://help.logmein.com/pkb_Home?l=en_US&c=products%3Almihamachi2
