### ISSUE TITLE
Can't configure Hamachi

### ISSUE THREAD

**Issue by kobligo** [ztefn/haguichi#32]
On launch, Haguichi tells me I need to configure Hamachi. Clicking the Configure button brings up the Linux user password prompt. (I'm on Ubuntu 20.04.1 using Flatpak Haguichi.) After typing it in and hitting Return Haguichi does nothing, and that's it.

I was wondering, is there a non-GUI way of performing this step until the issue is fixed?

**Comment by ztefn** [comment]
@kobligo This is a known issue with the Flatpak version due to the way the sandboxing / mounting of directories works. The configure action is actually executed but Haguichi cannot see that it was successful, because the Hamachi configuration directory is not immediately mounted by Flatpak. Simply quit and relaunch Haguichi and you will not see the configure step again.

I have a [fix](https://github.com/ztefn/haguichi/commit/6dd28893a4d92fe70ac05386f6d5f775421c6de6) (workaround) for this prepared, but I haven't made a new release yet.

Btw the non-GUI way would be to add the line `Ipc.User username` to the file **/var/lib/logmein-hamachi/h2-engine-override.cfg** where _username_ is your actual username.

**Comment by xenicle** [comment]
I Have same problem on Linux Mint 20, but after added `Ipc.User username` to /var/lib/logmein-hamachi/h2-engine-override.cfg file and restarted Hamachi deamon (with `sudo systemctl restart logmein-hamachi`) and quit/restart Haguichi it continue to ask for Hamachi config. I've also tried with the deb from ppa:webupd8team/haguichi.

**Comment by ztefn** [comment]
@xenicle What does Hamachi itself report when you run the command `hamachi` without sudo?

**Comment by ztefn** [comment]
I'm closing this issue for now because version 1.4.3 with the workaround for Flatpak has been released and there has not been any response from @xenicle to my question.
