### ISSUE TITLE
Treat versioned tags as immutable

### ISSUE THREAD

**Issue by cassidyjames** [ztefn/haguichi#34]
Part of the AppCenter review process uses a comparison between previously-released tags and the submitted tag to speed up the review process. However, if these tags are changed or deleted, it means the app must be reviewed from scratch each time—which is time consuming and introduces a significant delay.

Instead, previous releases/tags should be treated as immutable to ensure a comparison can be made between the previous release and the latest release.

**Comment by ztefn** [comment]
@cassidyjames Thanks for letting me know, because I had no idea how your review process worked and would maybe never have found out removing those tags made things more difficult for you!

Haguichi releases for elementary OS are based on the master branch with the elementary specific tweaks applied on top of it. To accommodare this I have been using a single [elementary branch](https://github.com/ztefn/haguichi/tree/elementary) that is continuously rebased (and thus overwritten regularly). I think however, as long as I don't remove the tags themselves the code should behind it will be preserved as well. So I can promise not to remove the current 1.143.0 release tag at least until a future release has passed review. Does that sound okay to you?

Alternatively, I could even create a separate branch for each final release that will never gets touched again, much like the last one for [Loki](https://github.com/ztefn/haguichi/tree/elementary-loki). And put the tag on that branch.

**Comment by cassidyjames** [comment]
I am not sure exactly how rebasing would work while preserving the old tag. If that works, it sounds the easiest.

**Comment by ztefn** [comment]
Tags in git references a specific commit (hash). Apparently, rebasing or even deleting the whole branch would not in any way effect the tag and the commit it references. So yeah, as long as the tag itself is not removed everything should be fine.
