### ISSUE TITLE
Haguichi won't let me configure Hamachi

### ISSUE THREAD

**Issue by Nundir** [ztefn/haguichi#37]
Hello, when I launch the app, Haguichi asks me to configure Hamachi, however clicking the Configure button does nothing at all, which I think must be because I am using Awesome WM and he must try to execute a command that I don't have.
Do you have a solution for that (even if it involves doing the configuration manually via the CLI or a file) ?

Thank you

**Comment by ztefn** [comment]
Hi, maybe you see why configuring doesn't work in debug mode if you start Haguichi from CLI using:
`haguichi --debug`

Maybe its unable to gain (super user or root) privileges or using the wrong init system. Because what it will attempt to do (and what you indeed can do manually) is the following:
1. Stop/kill the hamachi daemon.
2. Add the line `Ipc.User username` to the file **/var/lib/logmein-hamachi/h2-engine-override.cfg** where _username_ is your actual username.
3. Restart the hamachi daemon

**Comment by ztefn** [comment]
@Nundir Have you been able to gather some debug output or other information?

**Comment by ztefn** [comment]
Closing this issue due to lack of response.
