### ISSUE TITLE
libappindicator3-1 package does not exist in Debian testing

### ISSUE THREAD

**Issue by vascowhite** [ztefn/haguichi#39]
Hi,

This is a great project, I use it all the time!
I am trying to install this on debian testing (bullseye). When I attempt to install it I get the following error:-

```text
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 haguichi : Depends: libappindicator3-1 but it is not installable
            Recommends: dconf-cli but it is not going to be installed
            Recommends: desktop-file-utils but it is not going to be installed
            Recommends: dnsutils
E: Unable to correct problems, you have held broken packages.
```
I did some searching and found this:-
https://support.delta.chat/t/debian-package-fails-to-install-on-testing-bullseye-nonexisting-dependency/1364

> libappindicator3-1 package does not exist in Debian testing (and probably won’t in the upcoming stable release). The package is subject to be removed from 1 Debian 1.

> Proposed solution by Debian: migrate to libayatana-appindicator.

Is this in your future plans?
Any suggestions on a work around?

**Comment by ztefn** [comment]
Thanks for reporting this! I was aware that libappindicator had been forked into this new project because the original project was unmaintained. But I didn't know it was already available in the package repositories for a while intended to replace the original library.

Knowing this now, I will plan to replace the appindicator library for the upcoming release (version 1.4.4).

As work around you could build from source (appindicator is not enabled by default) or use the [flatpak](https://flathub.org/apps/details/com.github.ztefn.haguichi) version.

**Comment by vascowhite** [comment]
Thanks for the quick reply.
I'll try building it myself, I have an aversion to flatpak that I can't explain :)

**Comment by ztefn** [comment]
News flash. Supporting `ayatana-appindicator` is easy, API appears to be the same. Just needs the [Meson build script](https://github.com/ztefn/haguichi/blob/master/src/meson.build) to be aware.

As for totally replacing `libappindicator`, this is a little premature. Seems to be a Debian-only crusade for now. Ubuntu folks [don't play along](https://bugs.launchpad.net/ubuntu/+source/libayatana-appindicator/+bug/1770146) and are keeping `libappindicator` in **main**.

So I decided to split deb packaging into separate branches for [Ubuntu](https://github.com/ztefn/haguichi/tree/deb-packaging-xenial) and [Debian](https://github.com/ztefn/haguichi/tree/deb-packaging-buster) so that they can have their own different dependencies (additional advantage is we can leave out the ubuntu-mono and Yaru icons as well).

Having separate build means separate [PPA repository](https://code.launchpad.net/~ztefn/+archive/ubuntu/haguichi-debian). This PPA now contains the stable release (version 1.4.3) with a [patch](https://github.com/ztefn/haguichi/commit/8f06713a9b5a7b4e1839ccfc7b82bbaaab16f45d) for the build script to use `ayatana-appindicator`. [Here](https://code.launchpad.net/~ztefn/+recipe/haguichi-debian) you can find the Launchpad build recipe.

In order to install Haguichi from this PPA for Debian:
`sudo sh -c 'echo "deb http://ppa.launchpad.net/ztefn/haguichi-debian/ubuntu bionic main" > /etc/apt/sources.list.d/haguichi-debian.list'`
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB75B0EBE2C821AC`
`sudo apt update`
`sudo apt install -y haguichi`

I will soon update the [installation instructions for Debian](https://haguichi.net/download/#debian) on the website to these commands if no problems arise.

**Comment by vascowhite** [comment]
This worked perfectly.
Thank you for the quick action, having the separate repository makes perfect sense.

It's nice to have the icon back :)

**Comment by ztefn** [comment]
Good to hear! I have updated the instructions on the website.

Thanks for the beer! 🍺️
You are now in the [Hall of Fame](https://haguichi.net/donate/#donations). 🎉️
