### ISSUE TITLE
Package as Flatpak for elementary OS 6

### ISSUE THREAD

**Issue by danrabbit** [ztefn/haguichi#42]
As you might have heard, AppCenter is going Flatpak! For elementary OS 6, we will not longer be accepting Debian packaging, so your app will need to be updated.

We have documentation on our developer guide for writing your Flatpak manifest here: https://docs.elementary.io/develop/writing-apps/our-first-app/packaging#flatpak-manifest

Also, in case you missed it, elementary OS 6 beta 2 is [now available](https://builds.elementary.io). This is a great time to get your app packaged up as Flatpak and test that everything is working before the final release. AppCenter submission for OS 6 will be open soon, so don't delay :)

**Comment by ztefn** [comment]
At the moment I'm not very eager to spend more time on elementary OS packaging while there are so many outstanding issues and unknowns.

I have reported stylesheet issues ([#1004](https://github.com/elementary/stylesheet/issues/1004) and [#1005](https://github.com/elementary/stylesheet/issues/1005)) for elementary OS 6 (beta) which are being ignored and I don't like the prospect on have to ship even more custom CSS to work around these issues. I would rather ditch the primary color altogether.

There is no mention about the situation for Wingpanel indicators (other than [here](https://github.com/elementary/wingpanel/issues/353)) in elementary OS 6 and Flatpak packaging. The use case has not changed since elementary OS 5 but it seems to be getting dropped silently based on just technical debt or merit.

Also it's totally unclear for me how you intend to support packaging for both elementary OS 5 and 6 since they will have a completely diverged build process (one Debian and other Flatpak). Or is elementary OS 5 going Flatpak too? And why is my release for elementary OS 5 [still in limbo](https://github.com/elementary/houston/issues/826)?

Please get your issues solved and have a complete packaging story, not just how to write a minimal Flatpak manifest (already [have one](https://github.com/ztefn/haguichi/blob/master/com.github.ztefn.haguichi.json) for [Flathub](https://flathub.org/apps/details/com.github.ztefn.haguichi)) but also how the rest of the build pipeline works. Then I will take a look at this again.

**Comment by ztefn** [comment]
@danrabbit I have submitted tag [1.145.0](https://github.com/ztefn/haguichi/tree/1.145.0) for review.

Regarding: _Future releases/tags of your app will be automatically submitted for review and approval._

This might not be such a good idea as I will have non-elementary specific release tags.

In other news, I have given up on pushing updates for Hera because the submission process via Houston is completely broken.

**Comment by ztefn** [comment]
And so another issue was filed... elementary/appcenter-reviews#90

Are you sure you want apps in AppCenter? Because your app submission process experience is truly dreadful, lacking any documentation, feedback or support.

**Comment by ztefn** [comment]
Manually opened pull request elementary/appcenter-reviews#98. Closing this issue.

**Comment by danrabbit** [comment]
Hey @ztefn sorry for the bumpy experience. There's kind of a lot going on right now and very few of us to manage all of the folks who are requesting support. Thanks for your patience
