### ISSUE TITLE
Use Gtk.Application.inhibit instead of manually using login interface

### ISSUE THREAD

**Issue by danirabbit** [ztefn/haguichi#48]
Hey there, while reviewing your app for AppCenter I noticed that you're manually touching the login interface in order to implement inhibiting. Gtk.Application has a built-in inhibit method documented here: https://valadoc.org/gtk+-3.0/Gtk.Application.inhibit.html

I'd imagine this is something that will probably be a portal soon so that users give informed consent to apps who want to request inhibit

**Comment by ztefn** [comment]
Unfortunately, the functionalty that `Gtk.Application.inhibit` provides is different from what Haguichi needs. Haguichi does not start any operation that should not be interrupted. It merely listens for a [PrepareForSleep()](https://www.freedesktop.org/software/systemd/man/org.freedesktop.login1.html#Signals) signal and then says "Hold on, let me quickly disconnect the Hamachi client before going to sleep..." in order to close the connection cleanly. And later on, when waking up, the connection is restored again. See the code at: https://github.com/ztefn/haguichi/blob/master/src/inhibitor.vala

Still, I'd love to hear if you know any other Gtk api that does provide this functionality.

**Comment by danrabbit** [comment]
Thanks for clarifying that! I don't know about that off the top of my head, but I'll ask around :)

**Comment by danrabbit** [comment]
It looks like LibPortal might be the route to go here. It seems like it has methods here to watch the session state: https://github.com/flatpak/libportal/blob/master/libportal/inhibit.c#L655

Or you could manually use the inhibit portal over dbus as described here: https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Inhibit

And that should let you drop the login dbus interface

**Comment by donaldshimoda** [comment]
This is involved in the fact is ask again user password when disconnects?

**Comment by ztefn** [comment]
> This is involved in the fact is ask again user password when disconnects?

No. This is about application programming interfaces to receive signals when the computer goes to sleep or wakes up again.

**Comment by ztefn** [comment]
> This is involved in the fact is ask again user password when disconnects?

No. This is about application programming interfaces to receive signals when the computer goes to sleep or wakes up again.

**Comment by donaldshimoda** [comment]
Is possible to avoid asking password some times the network disconnect? And say sometimes because dont ask everytime, seems o ask only when a timeout trying reconnect fails.

Bets regards

**Comment by ztefn** [comment]
> Is possible to avoid asking password some times the network disconnect? And say sometimes because dont ask everytime, seems o ask only when a timeout trying reconnect fails.

Haguichi only asks for a password when the hamachi service also needs to be (re)started when the daemon has crashed. Because hamachi runs as system service it requires administrative permission.

You might configure a service to automatically restart the daemon, but I'm not sure how it would interact with the existing init.d service wrapper for hamachi (/etc/init.d/logmein-hamachi).
https://ma.ttias.be/auto-restart-crashed-service-systemd/

Now, please using this issue for unrelated questions. Open a new issue instead or drop me an e-mail.

**Comment by ztefn** [comment]
Relevant issue in xdg-desktop-portal: flatpak/xdg-desktop-portal#137

**Comment by ztefn** [comment]
Specific dbus interface to watch session state changes:
https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-signal-org-freedesktop-portal-Inhibit.StateChanged

> The StateChanged signal is sent to active monitoring sessions when the session state changes.
> 
> When the session state changes to 'Query End', clients with active monitoring sessions are expected to respond by calling [QueryEndResponse()](https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-method-org-freedesktop-portal-Inhibit.QueryEndResponse) within a second of receiving the StateChanged signal. They may call [Inhibit()](https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-method-org-freedesktop-portal-Inhibit.Inhibit) first to inhibit logout, to prevent the session from proceeding to the Ending state.

Implementation in libportal appears to be [Portal.session_monitor_start](https://valadoc.org/libportal/Xdp.Portal.session_monitor_start.html)
> When the state changes, the [Portal:session-state-changed](https://valadoc.org/libportal/Xdp.Portal.session_state_changed.html) signal is emitted.

> public signal void session_state_changed (bool screensaver_active, [LoginSessionState](https://valadoc.org/libportal/Xdp.LoginSessionState.html) **session_state**)
> 
> Emitted when session state monitoring is enabled and the **state of the login session changes** or the screensaver is activated or deactivated.

> The values of this enum are returned in the Portal::session-state-changed signal to indicate the current state of the user session.
> 
> Enum values:
>    [ENDING](https://valadoc.org/libportal/Xdp.LoginSessionState.ENDING.html) - the session is about to end
>    [QUERY_END](https://valadoc.org/libportal/Xdp.LoginSessionState.QUERY_END.html) - **the session is in the query end phase, during which applications can save their state or inhibit the session from ending**
>    [RUNNING](https://valadoc.org/libportal/Xdp.LoginSessionState.RUNNING.html) - the session is running

**Comment by ztefn** [comment]
Implementation in GTK 3 (same in GTK 4, but documentation for prior version is more readable):
https://valadoc.org/gtk+-3.0/Gtk.Application.query_end.html

> [ Version ( since = "3.24.8" ) ]
> public signal void query_end ()
> 
> Emitted when the session manager is about to end the session, only if [GtkApplication::register-session](https://valadoc.org/gtk+-3.0/Gtk.Application.register_session.html) is true.
> 
> Applications can connect to this signal and call [inhibit](https://valadoc.org/gtk+-3.0/Gtk.Application.inhibit.html) with gtk_application_inhibit_logout to delay the end of the session until state has been saved.

**Comment by ztefn** [comment]
Last few days I have tested both Gtk and LibPortal methods and it turned out inhibitors get totally ignored when the system is suspended by the user.

Also there are no QUERY_END or ENDING signals being sent when the system is suspended. Only logout and shutdown events seem to trigger those signals.

So unless the issue [Inhibit portal and PrepareForSleep signal #137](https://github.com/flatpak/xdg-desktop-portal/issues/137) in xdg-desktop-portal gets any traction I'm afraid we're stuck with using the `org.freedesktop.login1` dbus interface, just like [50 other applications currently on flathub](https://github.com/search?q=org%3Aflathub+org.freedesktop.login1&type=code).

Please reopen or create a new issue when there *is* a proper replacement.
