### ISSUE TITLE
Provide a label for alias name

### ISSUE THREAD

**Issue by donaldshimoda** [ztefn/haguichi#56]
I think $N return the destination computer alias, but only shows nick. Please add one for other computer alias. 
BTW is an amazing app, the configurable commands make my day

**Comment by ztefn** [comment]
The %N variable within commands is for nick(name) indeed. If there's an alias set on a member it will overwrite the (IPv4) address. So in your commands you can still use %A for the (alias) address.

**Comment by donaldshimoda** [comment]
Thanks for your quick response. I need to get the alias as name, not address , as defined in hamachi. For the target connection (not my own alias). If this is the function for %N this dont work. Always return the word NICK. Version 1.4.5

**Comment by ztefn** [comment]
I am not familiar with any alias as name. Can you give provide me the hamachi command and example output in which this alias name is available?

**Comment by ztefn** [comment]
> Always return the word NICK.

Do you mean the literal word **Nick** in the command preferences (see screenshot below)? That is just an example how the command would result into when parsed for a fictitious network member with nickname **Nick** and IP address **25.123.456.78**. When run on a network member it will get parsed with the nickname and address values for that specific member...

![Screenshot from 2023-01-15 02-27-35](https://user-images.githubusercontent.com/343442/212504659-e216b61d-6c31-4b50-b787-2a1718848330.png)

**Comment by donaldshimoda** [comment]
thanks again for your support

![Screenshot from 2023-01-14 22-42-33](https://user-images.githubusercontent.com/4336454/212520214-9b232009-8ae5-4892-8c22-6778626b054d.png)

i need to put in my command line this nick from the target computer. not my nick.
i need the target computer nick , the one setup with sudo hamachi set-nick command

right now the %N dotn work and always show the word Nick

![Screenshot from 2023-01-14 22-47-07](https://user-images.githubusercontent.com/4336454/212520300-cbfaca8d-68a3-4699-a656-8b9c482b28e9.png)

result

![Screenshot from 2023-01-14 22-48-03](https://user-images.githubusercontent.com/4336454/212520320-923274d4-2355-4548-8ba3-12ca892f165b.png)

result must be for the first item

ar_indu_triton.

I hope is clear, let me know

**Comment by donaldshimoda** [comment]
> When the command is actually run on a network member it will get parsed with the nickname and address values for that specific member...

Yes, this is the expected but no, it always return Nick world

**Comment by ztefn** [comment]
I think there is a bit of misunderstanding here.

The preferences window will always show **Nick** for **%N** no matter what. This is because its just an example. It doesn't use the "first item", "second item" or _any_ item from your network list.

The only situation where you will ever see the actual nick is _after_ you select the network member and then _run_ the command from the sidebar or right click menu.

So lets create an example command that is an actually valid command to print the nick in a terminal:
`%TERMINAL /bin/sh -c 'echo %N; exec bash'`

And add this command to Haguichi like this:
![Screenshot from 2023-01-15 14-27-29](https://user-images.githubusercontent.com/343442/212543539-78c8c973-73f1-41de-be99-c06fafd41bca.png)

Now select the member you want and press the button "Show Nick in Terminal" in the sidebar:
![Screenshot from 2023-01-15 14-28-09](https://user-images.githubusercontent.com/343442/212543691-e0293345-243b-46db-ae6d-d3f42226569d.png)

And voilà instead of **Nick** the actual nick of the selected member (in this example "ztefn") is printed in the terminal:
![Screenshot from 2023-01-15 14-29-16](https://user-images.githubusercontent.com/343442/212543733-b3041d8f-cec8-4b0d-8a0d-69a577e1629d.png)

**Comment by donaldshimoda** [comment]
Excellent
![Screenshot from 2023-01-15 09-41-05](https://user-images.githubusercontent.com/4336454/212544241-52adc780-16f8-4b77-a54d-0e70f39079fd.png)
, thanks! The misunderstanding origins in all other values are replaced ok in the preview panel but nick dont.
![Screenshot from 2023-01-15 09-41-05](https://user-images.githubusercontent.com/4336454/212544241-52adc780-16f8-4b77-a54d-0e70f39079fd.png)

**Comment by ztefn** [comment]
> Excellent thanks! The misunderstanding origins in all other values are replaced ok in the preview panel but nick dont.

The address 25.**123.456.78** and client ID 090-**123-456** are also just an examples and not an actual address or client ID from any network members (although by very small change it could actually match a real one).
