### ISSUE TITLE
How to resolve the blue dot issue?

### ISSUE THREAD

**Issue by Clearoad** [ztefn/haguichi#58]
Most tutorials seem to take into account the Windows version that has a graphical interface, how can I resolve this in the Haguichi?

**Comment by ztefn** [comment]
There's not much Haguichi can solve for you because a relayed connection is caused by firewall or router:
https://support.logmeininc.com/hamachi/help/which-ports-and-protocols-does-hamachi-use

If you need to set a static UDP port for Hamachi on Linux you can apparently do so in the `h2-engine-override.cfg` file:
https://ubuntuforums.org/showthread.php?t=2387017&p=13826606#post13826606
